### ISSUE TITLE
Compiling iwbtc?

### ISSUE THREAD

**Issue by JakeTrock** [copy/iwbtc#2]
I was creating a json-based level editor, but I actually need to compile the code. I used the closure compiler you recommended from v86, because that's what cc.sh said it was missing, but for some reason, there's a missing file called iwbtc-all.js that's missing and I don't know where to find it...
command line excerpt(I use ubuntu)

`
jake@jake-pc:~/Desktop/iwbtc-master$ ./cc.sh
ls: cannot access 'iwbtc-all.js': No such file or directory
engine.js:3: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.
/** @define */
            ^
 
ERROR - Cannot read file clone.js: clone.js
 
1 error(s), 1 warning(s)
ls: cannot access 'iwbtc-all.js': No such file or directory
jake@jake-pc:~/Desktop/iwbtc-master$
`

**Comment by copy** [comment]
`iwbtc-all.js` is the output file, so it doens't matter that it's missing on the first run.

`clone.js` seems to be missing, which you can grab here: http://copy.sh/iw/clone.js.

You'll also have to fix the `@define` annotation, see [here](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#define-type-description).

**Comment by JakeTrock** [comment]
ok, I compiled it successfully, but to test the code I want to constantly make changes, is there any way to run the js files without compiling them?

**Comment by copy** [comment]
Yes, just loading all the JavaScript files directly should work.

**Comment by JakeTrock** [comment]
I tried including everything in the index.html file, but I still get an error...


`<script src="clone.js"></script><script src="audio.js"></script><script src="bitmap.js"></script><script src="editor.js"></script><script src="engine.js"></script><script src="externs.js"></script><script src="game_objects.js"></script><script src="keyboard.js"></script><script src="renderer.js"></script><script src="schnosm.js"></script><script src="storage.js"></script><script src="util.js"></script><script src="./levels/level1.js"></script>`



I didn't touch audio.js, is there any way I could fix this error?
`TypeError: Audio is not a constructor
AudioManager http://localhost:8080/iwbtc-master/audio.js:16:14
GameEngine http://localhost:8080/iwbtc-master/engine.js:61:18
<anonymous> http://localhost:8080/iwbtc-master/engine.js:33:14
`

**Comment by copy** [comment]
Don't include `externs.js`.
